<?php

    $colors = ["AliceBlue",
    "AntiqueWhite",
    "Aqua",
    "Aquamarine",
    "Azure",
    "Beige",
    "Bisque",
    "Black",
    "BlanchedAlmond",
    "Blue",
    "BlueViolet",
    "Brown",
    "BurlyWood",
    "CadetBlue",
    "Chartreuse",
    "Chocolate",
    "Coral",
    "CornflowerBlue",
    "Cornsilk",
    "Crimson",
    "Cyan",
    "DarkBlue",
    "DarkCyan",
    "DarkGoldenRod",
    "DarkGray",
    "DarkGrey",
    "DarkGreen",
    "DarkKhaki",
    "DarkMagenta",
    "DarkOliveGreen",
    "Darkorange",
    "DarkOrchid",
    "DarkRed",
    "DarkSalmon",
    "DarkSeaGreen",
    "DarkSlateBlue",
    "DarkSlateGray",
    "DarkSlateGrey",
    "DarkTurquoise",
    "DarkViolet",
    "DeepPink",
    "DeepSkyBlue",
    "DimGray",
    "DimGrey",
    "DodgerBlue",
    "FireBrick",
    "FloralWhite",
    "ForestGreen",
    "Fuchsia",
    "Gainsboro",
    "GhostWhite",
    "Gold",
    "GoldenRod",
    "Gray",
    "Grey",
    "Green",
    "GreenYellow",
    "HoneyDew",
    "HotPink",
    "IndianRed",
    "Indigo",
    "Ivory",
    "Khaki",
    "Lavender",
    "LavenderBlush",
    "LawnGreen",
    "LemonChiffon",
    "LightBlue",
    "LightCoral",
    "LightCyan",
    "LightGoldenRodYellow",
    "LightGray",
    "LightGrey",
    "LightGreen",
    "LightPink",
    "LightSalmon",
    "LightSeaGreen",
    "LightSkyBlue",
    "LightSlateGray",
    "LightSlateGrey",
    "LightSteelBlue",
    "LightYellow",
    "Lime",
    "LimeGreen",
    "Linen",
    "Magenta",
    "Maroon",
    "MediumAquaMarine",
    "MediumBlue",
    "MediumOrchid",
    "MediumPurple",
    "MediumSeaGreen",
    "MediumSlateBlue",
    "MediumSpringGreen",
    "MediumTurquoise",
    "MediumVioletRed",
    "MidnightBlue",
    "MintCream",
    "MistyRose",
    "Moccasin",
    "NavajoWhite",
    "Navy",
    "OldLace",
    "Olive",
    "OliveDrab",
    "Orange",
    "OrangeRed",
    "Orchid",
    "PaleGoldenRod",
    "PaleGreen",
    "PaleTurquoise",
    "PaleVioletRed",
    "PapayaWhip",
    "PeachPuff",
    "Peru",
    "Pink",
    "Plum",
    "PowderBlue",
    "Purple",
    "Red",
    "RosyBrown",
    "RoyalBlue",
    "SaddleBrown",
    "Salmon",
    "SandyBrown",
    "SeaGreen",
    "SeaShell",
    "Sienna",
    "Silver",
    "SkyBlue",
    "SlateBlue",
    "SlateGray",
    "SlateGrey",
    "Snow",
    "SpringGreen",
    "SteelBlue",
    "Tan",
    "Teal",
    "Thistle",
    "Tomato",
    "Turquoise",
    "Violet",
    "Wheat",
    "White",
    "WhiteSmoke",
    "Yellow",
    "YellowGreen"];
$data = array(
    array("NAME"=>"Nola","CITY"=>"Cisano sul Neva","TEAM_ID"=>1),
    array("NAME"=>"Donovan","CITY"=>"Enna","TEAM_ID"=>2),
    array("NAME"=>"Ahmed","CITY"=>"Siculiana","TEAM_ID"=>3),
    array("NAME"=>"Aidan","CITY"=>"Grande Cache","TEAM_ID"=>4),
    array("NAME"=>"Shelby","CITY"=>"Oosterhout","TEAM_ID"=>5),
    array("NAME"=>"Cherokee","CITY"=>"Hanret","TEAM_ID"=>6),
    array("NAME"=>"Emily","CITY"=>"Zuienkerke","TEAM_ID"=>7),
    array("NAME"=>"Cooper","CITY"=>"Adelaide","TEAM_ID"=>8),
    array("NAME"=>"Chaim","CITY"=>"Wels","TEAM_ID"=>9),
    array("NAME"=>"Dara","CITY"=>"Wazirabad","TEAM_ID"=>10),
    array("NAME"=>"Alexandra","CITY"=>"Chattanooga","TEAM_ID"=>11),
    array("NAME"=>"Indigo","CITY"=>"Merseburg","TEAM_ID"=>12),
    array("NAME"=>"Kane","CITY"=>"Terrance","TEAM_ID"=>13),
    array("NAME"=>"Samantha","CITY"=>"Speyer","TEAM_ID"=>14),
    array("NAME"=>"Britanney","CITY"=>"Avadi","TEAM_ID"=>15),
    array("NAME"=>"Kenyon","CITY"=>"Merbes-Sainte-Marie","TEAM_ID"=>16),
    array("NAME"=>"Brendan","CITY"=>"Marcinelle","TEAM_ID"=>17),
    array("NAME"=>"Zorita","CITY"=>"Winnipeg","TEAM_ID"=>18),
    array("NAME"=>"Lee","CITY"=>"Shaftesbury","TEAM_ID"=>19),
    array("NAME"=>"Eden","CITY"=>"Visso","TEAM_ID"=>20),
    array("NAME"=>"Michael","CITY"=>"Limena","TEAM_ID"=>21),
    array("NAME"=>"Medge","CITY"=>"Belém","TEAM_ID"=>22),
    array("NAME"=>"Curran","CITY"=>"Mandasor","TEAM_ID"=>23),
    array("NAME"=>"Brynne","CITY"=>"Santa Marina","TEAM_ID"=>24),
    array("NAME"=>"Peter","CITY"=>"Virelles","TEAM_ID"=>25),
    array("NAME"=>"Abdul","CITY"=>"Salamanca","TEAM_ID"=>26),
    array("NAME"=>"Aline","CITY"=>"Bilbo","TEAM_ID"=>27),
    array("NAME"=>"Fulton","CITY"=>"Akola","TEAM_ID"=>28),
    array("NAME"=>"Kasper","CITY"=>"Weymouth","TEAM_ID"=>29),
    array("NAME"=>"Charles","CITY"=>"Angoulême","TEAM_ID"=>30),
    array("NAME"=>"Talon","CITY"=>"Multan","TEAM_ID"=>31),
    array("NAME"=>"Iliana","CITY"=>"Oudekapelle","TEAM_ID"=>32),
    array("NAME"=>"Tiger","CITY"=>"Westkapelle","TEAM_ID"=>33),
    array("NAME"=>"Claudia","CITY"=>"Erie","TEAM_ID"=>34),
    array("NAME"=>"Cyrus","CITY"=>"Cumnock","TEAM_ID"=>35),
    array("NAME"=>"Bertha","CITY"=>"Nellore","TEAM_ID"=>36),
    array("NAME"=>"Otto","CITY"=>"Auburn","TEAM_ID"=>37),
    array("NAME"=>"Maite","CITY"=>"Grimsby","TEAM_ID"=>38),
    array("NAME"=>"Jerry","CITY"=>"Warburg","TEAM_ID"=>39),
    array("NAME"=>"Vance","CITY"=>"Juneau","TEAM_ID"=>40),
    array("NAME"=>"Lilah","CITY"=>"Oevel","TEAM_ID"=>41),
    array("NAME"=>"Whitney","CITY"=>"Penrith","TEAM_ID"=>42),
    array("NAME"=>"Karly","CITY"=>"Robechies","TEAM_ID"=>43),
    array("NAME"=>"Maggy","CITY"=>"Lauro de Freitas","TEAM_ID"=>44),
    array("NAME"=>"Holmes","CITY"=>"Meldert","TEAM_ID"=>45),
    array("NAME"=>"Liberty","CITY"=>"Montague","TEAM_ID"=>46),
    array("NAME"=>"Dawn","CITY"=>"Saint-Médard-en-Jalles","TEAM_ID"=>47),
    array("NAME"=>"Tasha","CITY"=>"Alexandria","TEAM_ID"=>48),
    array("NAME"=>"Rigel","CITY"=>"Ashburton","TEAM_ID"=>49),
    array("NAME"=>"Clark","CITY"=>"Diano Arentino","TEAM_ID"=>50),
    array("NAME"=>"Nicholas","CITY"=>"Wyoming","TEAM_ID"=>51),
    array("NAME"=>"Mariam","CITY"=>"Salerno","TEAM_ID"=>52),
    array("NAME"=>"Alisa","CITY"=>"Sambalpur","TEAM_ID"=>53),
    array("NAME"=>"Chadwick","CITY"=>"Meißen","TEAM_ID"=>54),
    array("NAME"=>"Ali","CITY"=>"Leerbeek","TEAM_ID"=>55),
    array("NAME"=>"Maia","CITY"=>"Hatfield","TEAM_ID"=>56),
    array("NAME"=>"McKenzie","CITY"=>"Arbre","TEAM_ID"=>57),
    array("NAME"=>"Julian","CITY"=>"Carlisle","TEAM_ID"=>58),
    array("NAME"=>"Vivien","CITY"=>"Barrow-in-Furness","TEAM_ID"=>59),
    array("NAME"=>"Zoe","CITY"=>"Brahmapur","TEAM_ID"=>60),
    array("NAME"=>"Jordan","CITY"=>"Río Hurtado","TEAM_ID"=>61),
    array("NAME"=>"Pandora","CITY"=>"Rhisnes","TEAM_ID"=>62),
    array("NAME"=>"Shoshana","CITY"=>"Dumfries","TEAM_ID"=>63),
    array("NAME"=>"Ezekiel","CITY"=>"Stalhille","TEAM_ID"=>64),
    array("NAME"=>"Xandra","CITY"=>"Weesp","TEAM_ID"=>65),
    array("NAME"=>"Mannix","CITY"=>"Jonqui�re","TEAM_ID"=>66),
    array("NAME"=>"Mufutau","CITY"=>"Kailua","TEAM_ID"=>67),
    array("NAME"=>"Lyle","CITY"=>"Boise","TEAM_ID"=>68),
    array("NAME"=>"Lilah","CITY"=>"Denderbelle","TEAM_ID"=>69),
    array("NAME"=>"Luke","CITY"=>"Meetkerke","TEAM_ID"=>70),
    array("NAME"=>"Mari","CITY"=>"Louvain-la-Neuve","TEAM_ID"=>71),
    array("NAME"=>"Lacy","CITY"=>"Groot-Bijgaarden","TEAM_ID"=>72),
    array("NAME"=>"Cora","CITY"=>"Porpetto","TEAM_ID"=>73),
    array("NAME"=>"Chelsea","CITY"=>"Acquafondata","TEAM_ID"=>74),
    array("NAME"=>"Curran","CITY"=>"Shawinigan","TEAM_ID"=>75),
    array("NAME"=>"Galena","CITY"=>"Tuscaloosa","TEAM_ID"=>76),
    array("NAME"=>"Karyn","CITY"=>"Huesca","TEAM_ID"=>77),
    array("NAME"=>"Kirk","CITY"=>"Halanzy","TEAM_ID"=>78),
    array("NAME"=>"Bryar","CITY"=>"Folx-les-Caves","TEAM_ID"=>79),
    array("NAME"=>"Gannon","CITY"=>"Wisbech","TEAM_ID"=>80),
    array("NAME"=>"Hadassah","CITY"=>"Nieuwmunster","TEAM_ID"=>81),
    array("NAME"=>"Craig","CITY"=>"Socchieve","TEAM_ID"=>82),
    array("NAME"=>"Charity","CITY"=>"Musselburgh","TEAM_ID"=>83),
    array("NAME"=>"Daniel","CITY"=>"Fresno","TEAM_ID"=>84),
    array("NAME"=>"April","CITY"=>"Maullín","TEAM_ID"=>85),
    array("NAME"=>"Dominique","CITY"=>"Buken","TEAM_ID"=>86),
    array("NAME"=>"Gillian","CITY"=>"Zeitz","TEAM_ID"=>87),
    array("NAME"=>"Ryder","CITY"=>"Maracanaú","TEAM_ID"=>88),
    array("NAME"=>"Dorothy","CITY"=>"San Marcello","TEAM_ID"=>89),
    array("NAME"=>"Deborah","CITY"=>"Kansas City","TEAM_ID"=>90),
    array("NAME"=>"Elton","CITY"=>"Sauvenire","TEAM_ID"=>91),
    array("NAME"=>"Ciaran","CITY"=>"Daknam","TEAM_ID"=>92),
    array("NAME"=>"Astra","CITY"=>"Dion-Valmont","TEAM_ID"=>93),
    array("NAME"=>"Nadine","CITY"=>"Kettering","TEAM_ID"=>94),
    array("NAME"=>"Gary","CITY"=>"Campobasso","TEAM_ID"=>95),
    array("NAME"=>"Leilani","CITY"=>"Zerba","TEAM_ID"=>96),
    array("NAME"=>"Kitra","CITY"=>"Rimouski","TEAM_ID"=>97),
    array("NAME"=>"Mari","CITY"=>"Bois-de-Villers","TEAM_ID"=>98),
    array("NAME"=>"Howard","CITY"=>"Ramsel","TEAM_ID"=>99),
    array("NAME"=>"Nyssa","CITY"=>"Gander","TEAM_ID"=>100),
    array("NAME"=>"Victor","CITY"=>"Fürth","TEAM_ID"=>101),
    array("NAME"=>"Sybill","CITY"=>"Orvieto","TEAM_ID"=>102),
    array("NAME"=>"Ora","CITY"=>"Chalon-sur-Saône","TEAM_ID"=>103),
    array("NAME"=>"Kane","CITY"=>"Beausejour","TEAM_ID"=>104),
    array("NAME"=>"Cathleen","CITY"=>"Nasino","TEAM_ID"=>105),
    array("NAME"=>"Hillary","CITY"=>"Harlech","TEAM_ID"=>106),
    array("NAME"=>"Ezekiel","CITY"=>"Massenhoven","TEAM_ID"=>107),
    array("NAME"=>"Lila","CITY"=>"Wichita","TEAM_ID"=>108),
    array("NAME"=>"Maris","CITY"=>"Portezuelo","TEAM_ID"=>109),
    array("NAME"=>"Myles","CITY"=>"Hannut","TEAM_ID"=>110),
    array("NAME"=>"Stella","CITY"=>"Cairo Montenotte","TEAM_ID"=>111),
    array("NAME"=>"Denise","CITY"=>"Portland","TEAM_ID"=>112),
    array("NAME"=>"Yasir","CITY"=>"Sauvenire","TEAM_ID"=>113),
    array("NAME"=>"Cyrus","CITY"=>"Campolieto","TEAM_ID"=>114),
    array("NAME"=>"Carissa","CITY"=>"Salon-de-Provence","TEAM_ID"=>115),
    array("NAME"=>"Ashton","CITY"=>"Mango","TEAM_ID"=>116),
    array("NAME"=>"Caesar","CITY"=>"Acosse","TEAM_ID"=>117),
    array("NAME"=>"Levi","CITY"=>"Gaggio Montano","TEAM_ID"=>118),
    array("NAME"=>"Tanek","CITY"=>"Aquila d'Arroscia","TEAM_ID"=>119),
    array("NAME"=>"Nadine","CITY"=>"Nakusp","TEAM_ID"=>120),
    array("NAME"=>"Tate","CITY"=>"Pomarolo","TEAM_ID"=>121),
    array("NAME"=>"Gil","CITY"=>"Molenbeersel","TEAM_ID"=>122),
    array("NAME"=>"Hakeem","CITY"=>"Ramsel","TEAM_ID"=>123),
    array("NAME"=>"Mary","CITY"=>"GŽrompont","TEAM_ID"=>124),
    array("NAME"=>"Irene","CITY"=>"Ways","TEAM_ID"=>125),
    array("NAME"=>"Marvin","CITY"=>"Tramutola","TEAM_ID"=>126),
    array("NAME"=>"Nola","CITY"=>"Folx-les-Caves","TEAM_ID"=>127),
    array("NAME"=>"Emerson","CITY"=>"Wortel","TEAM_ID"=>128),
    array("NAME"=>"Yoshi","CITY"=>"Selva di Cadore","TEAM_ID"=>129),
    array("NAME"=>"Mikayla","CITY"=>"Gorbea","TEAM_ID"=>130),
    array("NAME"=>"Cedric","CITY"=>"Trowbridge","TEAM_ID"=>131),
    array("NAME"=>"Damon","CITY"=>"Renlies","TEAM_ID"=>132),
    array("NAME"=>"Marny","CITY"=>"Getafe","TEAM_ID"=>133),
    array("NAME"=>"Adam","CITY"=>"El Monte","TEAM_ID"=>134),
    array("NAME"=>"Ruth","CITY"=>"Raymond","TEAM_ID"=>135),
    array("NAME"=>"Marvin","CITY"=>"Wetaskiwin","TEAM_ID"=>136),
    array("NAME"=>"Ori","CITY"=>"Seilles","TEAM_ID"=>137),
    array("NAME"=>"Channing","CITY"=>"Vaux-sous-ChŽvremont","TEAM_ID"=>138),
    array("NAME"=>"Keane","CITY"=>"Huppaye","TEAM_ID"=>139),
    array("NAME"=>"Ralph","CITY"=>"Herne","TEAM_ID"=>140),
    array("NAME"=>"Melanie","CITY"=>"Bovigny","TEAM_ID"=>141),
    array("NAME"=>"Rajah","CITY"=>"Villers-la-Tour","TEAM_ID"=>142),
    array("NAME"=>"Simon","CITY"=>"Lowell","TEAM_ID"=>143),
    array("NAME"=>"Shelby","CITY"=>"Guarulhos","TEAM_ID"=>144),
    array("NAME"=>"Alexander","CITY"=>"Maglie","TEAM_ID"=>145),
    array("NAME"=>"Seth","CITY"=>"Geer","TEAM_ID"=>146),
    array("NAME"=>"Donovan","CITY"=>"Jette","TEAM_ID"=>147),
);

$contents = [
        [
            "TYPE" => 'DOG',
            "LOGO" => 'https://image.ibb.co/nOsuJo/dog.jpg',
        ],
        [
            "TYPE" => 'PARROT',
            "LOGO" => 'https://image.ibb.co/nbiC4T/parrot.jpg',
        ],
        [
            "TYPE" => 'CAT',
            "LOGO" => 'https://image.ibb.co/dfyn4T/cat_1.jpg',
        ],
    ];
$env = json_decode(file_get_contents('config.json'), true);
$user = $env['DB']['USER'];
$pass = $env['DB']['PASS'];
$end_pt = $env['DB']['HOST'];

$conn = mysqli_connect($end_pt, $user, $pass, $env['DB']['NAME']);

if (!$conn) {
    echo 'BAD';
}
$conn->query("DROP TABLE IF EXISTS INFO");
$conn->query("CREATE TABLE INFO (`ID` INT NOT NULL AUTO_INCREMENT, `COLOR` VARCHAR(50), PRIMARY KEY(ID));");
if (!$conn) {
    echo mysqli_error($conn);
}
$conn->query("DROP TABLE IF EXISTS TEAMS");
$conn->query("CREATE TABLE TEAMS (`ID` INT NOT NULL AUTO_INCREMENT, `NAME` VARCHAR(50) NOT NULL, `CITY` VARCHAR(50), `TEAM_ID` INT NOT NULL, PRIMARY KEY (ID));");
if (!$conn) {
    echo mysqli_error($conn);
}
$conn->query("DROP TABLE IF EXISTS CONTENT");
$conn->query("CREATE TABLE CONTENT (`ID` INT NOT NULL AUTO_INCREMENT, `TYPE` VARCHAR(50) NOT NULL, `LOGO` VARCHAR(50), PRIMARY KEY (ID));");
if (!$conn) {
    echo mysqli_error($conn);
}


foreach ($data as $index => $datum) {
    $statement = $conn->prepare("INSERT INTO TEAMS (NAME, CITY, TEAM_ID) VALUES (?, ?, ?)");
     if (!$statement) {
         print_r(mysqli_error($conn));
     }
    $statement->bind_param('ssi', $datum['NAME'],$datum['CITY'], $datum['TEAM_ID']);
    $statement->execute();
    $statement->close();
}

foreach ($colors as $color) {
    $statement = $conn->prepare("INSERT INTO INFO (COLOR) VALUES (?)");
    $statement->bind_param('s', $color);
    $statement->execute();
    $statement->close();
}

foreach ($contents as $key => $content) {
    $statement = $conn->prepare("INSERT INTO CONTENT (TYPE, LOGO) VALUES (?, ?)");
    if (!$statement) {
       print_r(mysqli_error($conn));
    }
    $statement->bind_param('ss', $content['TYPE'],$content['LOGO']);
    $statement->execute();
    $statement->close();
}